repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
        - id: isort
          name: isort
          stages: [commit]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
        - id: black
          name: black
          stages: [commit]
          language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    # -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    #-   id: flake8
        exclude: ^docs/
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
