# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    # This leads to "excessive memory use"
    #python: "miniconda-latest"
    python: "mambaforge-22.9"
  apt_packages:
      - snapd
  jobs:
    # Read the docs needs a couple packages not in the environment file
    pre_install:
      - conda install -y cmake compilers sphinx sphinxcontrib-bibtex
      - conda install sphinx_rtd_theme>=1.3
    pre_build:
      - pwd
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq && chmod +x yq
      - ./yq -p yaml -o json wisdem/inputs/analysis_schema.yaml >| docs/schema/analysis_schema.json
      - ./yq -p yaml -o json wisdem/inputs/modeling_schema.yaml >| docs/schema/modeling_schema.json
      - sed -i -s '0,/properties/s//definitions/' docs/schema/modeling_schema.json
      - sed -i -s '0,/properties/s//definitions/' docs/schema/analysis_schema.json
      #- sed -i -s -e '/properties/{s//definitions/;:a' -e '$!N;$!ba' -e '}' docs/schema/modeling_schema.json
      #- sed -i -s -e '/properties/{s//definitions/;:a' -e '$!N;$!ba' -e '}' docs/schema/analysis_schema.json


# Shouldn't need conda for building the docs, but it is an option
conda:
  environment: environment.yml


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
#  system_packages: true
