general:
    verbosity: False

yaml:
    validate: False
    path2schema: wisdem/wisdem/assemblies/reference_turbines/IEAontology_schema.yaml

xfoil:
    path       : /Users/pbortolo/work/1_wisdem/Xfoil/bin/xfoil

rotorse:
    n_aoa: 200        # Number of angles of attack used to define polars
    n_xy: 200         # Number of angles of coordinate points used to discretize each airfoil
    n_span: 30        # Number of spanwise stations used to define the blade properties

openfast:
    run_openfast: True
    Analysis_Level: 2
    FAST_ver: OpenFAST
    dev_branch: True
    FAST_exe: "/Users/nabbas/openfast/install/bin/openfast_dev"
    FAST_directory: "/Users/nabbas/Documents/TurbineModels/BAR/OpenFAST_Models/RotorSE_FAST_BAR_2010n_noRe_0_70_to_0_95"
    FAST_InputFile: "RotorSE_FAST_BAR_2010n_noRe.fst"
    path2dll: "/Users/nabbas/Documents/TurbineModels/BAR/OpenFAST_Models/ROSCO/build/libdiscon_flaps.dylib"
    Turbsim_exe: "/Users/nabbas/openfast/install/bin/turbsim_dev"
    FAST_namingOut: WISDEM_NREL5MW
    FAST_runDirectory: temp_bar
    cores: 1
    debug_level: 2
    
servose:
    n_pc: 20                        # Number of wind speeds to compute the power curve
    n_pc_spline: 200                # Number of wind speeds to spline the power curve 
    n_pitch_perf_surfaces: 20       # Number of pitch angles to determine the Cp-Ct-Cq-surfaces
    min_pitch_perf_surfaces: -5.    # Min pitch angle of the Cp-Ct-Cq-surfaces
    max_pitch_perf_surfaces: 30.    # Max pitch angle of the Cp-Ct-Cq-surfaces
    n_tsr_perf_surfaces: 20         # Number of tsr values to determine the Cp-Ct-Cq-surfaces
    min_tsr_perf_surfaces: 2.       # Min TSR of the Cp-Ct-Cq-surfaces
    max_tsr_perf_surfaces: 12.      # Max TSR of the Cp-Ct-Cq-surfaces
    n_U_perf_surfaces: 1            # Number of wind speeds to determine the Cp-Ct-Cq-surfaces
    LoggingLevel: 1 # {0: write no debug files, 1: write standard output .dbg-file, 2: write standard output .dbg-file and complete avrSWAP-array .dbg2-file
    F_LPFType: 1 # {1: first-order low-pass filter, 2: second-order low-pass filter}, [rad/s] (currently filters generator speed and pitch control signals)
    F_NotchType: 0 # Notch filter on generator speed and/or tower fore-aft motion (for floating) {0: disable, 1: generator speed, 2: tower-top fore-aft motion, 3: generator speed and tower-top fore-aft motion}
    IPC_ControlMode: 0 # Turn Individual Pitch Control (IPC) for fatigue load reductions (pitch contribution) {0: off, 1: 1P reductions, 2: 1P+2P reductions}
    VS_ControlMode: 2 # Generator torque control mode in above rated conditions {0: constant torque, 1: constant power, 2: TSR tracking PI control}
    PC_ControlMode: 1 # Blade pitch control mode {0: No pitch, fix to fine pitch, 1: active PI blade pitch control}
    Y_ControlMode: 0 # Yaw control mode {0: no yaw control, 1: yaw rate control, 2: yaw-by-IPC}
    SS_Mode: 1 # Setpoint Smoother mode {0: no setpoint smoothing, 1: introduce setpoint smoothing}
    WE_Mode: 2 # Wind speed estimator mode {0: One-second low pass filtered hub height wind speed, 1: Immersion and Invariance Estimator (Ortega et al.)}
    PS_Mode: 0 # Pitch saturation mode {0: no pitch saturation, 1: peak shaving, 2: Cp-maximizing pitch saturation, 3: peak shaving and Cp-maximizing pitch saturation}
    SD_Mode: 0 # Shutdown mode {0: no shutdown procedure, 1: pitch to max pitch at shutdown}
    Fl_Mode: 0 # Floating specific feedback mode {0: no nacelle velocity feedback, 1: nacelle velocity feedback}
    Flp_Mode: 0