general:
    folder_output: 20MW_opt
    fname_output: IEA20MW_FB

design_variables:
    blade:
        aero_shape:
            twist:
                flag: True             # Flag to optimize the twist
                inverse: False         # Flag to determine twist from the user-defined desired margin to stall (defined in constraints)
                n_opt: 6               # Number of control points along blade span
                max_decrease: 0.08722222222222221 # Maximum decrease for the twist in [rad] at the n_opt locations
                max_increase: 0.08722222222222221 # Maximum increase for the twist in [rad] at the n_opt locations
                index_start: 1         # Lock the first DV at blade root
                index_end: 5           # All DVs close to blade tip are active
            chord:
                flag: True             # Flag to optimize the chord
                n_opt: 6               # Number of control points along blade span
                max_decrease: 0.5      # Minimum multiplicative gain on existing chord at the n_opt locations
                max_increase: 2.       # Maximum multiplicative gain on existing chord at the n_opt locations
                index_start: 1         # Lock the first DV at blade root
                index_end: 5           # The last DV at blade tip is locked
        structure:
            - layer_name: Spar_Cap_SS
              n_opt: 6
              max_decrease: 0.8
              max_increase: 2.0
              index_start: 1
              index_end: 5
            - layer_name: Spar_Cap_PS
              n_opt: 6
              max_decrease: 0.8
              max_increase: 2.0
              index_start: 1
              index_end: 5
    tower:
        outer_diameter:
            flag: True
            lower_bound: 5.
            upper_bound: 10.0
        layer_thickness:
            flag: True
            lower_bound: 4.e-3
            upper_bound: 2.e-1
    monopile:
        outer_diameter:
            flag: True
            lower_bound: 5.
            upper_bound: 10.0
        layer_thickness:
            flag: True
            lower_bound: 4.e-3
            upper_bound: 2.e-1

merit_figure: LCOE

constraints:
    blade:
        strains_spar_cap_ss:
            flag: True         # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade suction side
            max:    3500.e-6   # Value of maximum strains [-]
            index_start: 1     # Do not enforce constraint at the first station from blade root of the n_opt from spar_cap_ss
            index_end: 5       # Do not enforce constraint at the last station at blade tip of the n_opt from spar_cap_ss
        strains_spar_cap_ps:
            flag: True         # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade pressure side
            max:    3500.e-6   # Value of maximum strains [-]
            index_start: 1     # Do not enforce constraint at the first station from blade root of the n_opt from spar_cap_ps
            index_end: 5       # Do not enforce constraint at the last station at blade tip of the n_opt from spar_cap_ps
        tip_deflection:
            flag: True
            margin: 1.4175
        stall:
            flag: True    # Constraint on minimum stall margin
            margin: 0.05233 # Value of minimum stall margin in [rad]
        moment_coefficient:
            flag: True
            max: 0.16
    tower:
        height_constraint:
            flag: False
            lower_bound: 1.e-2
            upper_bound: 1.e-2
        stress:
            flag: True
        global_buckling:
            flag: True
        shell_buckling:
            flag: True
        d_to_t:
            flag: True
            lower_bound: 120.0
            upper_bound: 2000.0
        taper:
            flag: True
            lower_bound: 0.2
        slope:
            flag: True
        frequency_1:
            flag: True
            lower_bound: 0.13
            upper_bound: 0.40
    monopile:
        stress:
            flag: True
        global_buckling:
            flag: True
        shell_buckling:
            flag: True
        d_to_t:
            flag: True
            lower_bound: 120.0
            upper_bound: 2000.0
        taper:
            flag: True
            lower_bound: 0.2
        slope:
            flag: True
        frequency_1:
            flag: True
            lower_bound: 0.13
            upper_bound: 0.40
        pile_depth:
            flag: True
            lower_bound: 0.0
        tower_diameter_coupling:
            flag: True

driver:
    optimization:
        flag: True         # Flag to enable optimization
        tol: 1.e-6          # Optimality tolerance
        max_major_iter: 30  # Maximum number of major design iterations (SNOPT)
        max_minor_iter: 1000 # Maximum number of minor design iterations (SNOPT)
        max_iter: 1         # Maximum number of iterations (SLSQP)
        solver: SLSQP       # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
        step_size: 1.e-2    # Step size for finite differencing
        form: forward       # Finite differencing mode, either forward or central

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql # Name of OpenMDAO recorder
