general:
    folder_output: outputs
    fname_output: doe_output
design_variables:
  blade:
    aero_shape:
      twist:
        flag: False  # Flag to optimize the twist
        inverse: False # Flag to determine twist from the user-defined desired margin to stall (defined in constraints)
        n_opt: 8     # Number of control points along blade span
        max_decrease: 0.08722222222222221 # Maximum decrease for the twist in [rad] at the n_opt locations
        max_increase: 0.08722222222222221 # Maximum increase for the twist in [rad] at the n_opt locations
      chord:
        flag: True     # Flag to optimize the chord
        n_opt: 8        # Number of control points along blade span
        min_gain: 0.2   # Nondimensional lower bound at the n_opt locations
        max_gain: 2.0   # Nondimensional upper bound at the n_opt locations
      af_positions:
        flag: False     # Flag to optimize the airfoil positions
        af_start: 4     # Index of the first airfoil from blade root that can have the location optimized. First airfoil is number 0. Last airfoil is always locked at blade tip.
    dac:
      te_flap_ext:
        flag: False
        min_ext: 0.0
        max_ext: 0.3
      te_flap_end:
        flag: False
        min_end: 0.3
        max_end: 1.0
  control:
    tsr:
      flag: False     # Flag to optimize the rotor tip speed ratio
      min_gain: 0.9   # Nondimensional lower bound
      max_gain: 1.1   # Nondimensional upper bound
    servo:
      pitch_control:
        flag: False
        omega_min: 0.1
        omega_max: 0.7
        zeta_min: 0.4
        zeta_max: 1.5
      torque_control:
        flag: False
        omega_min: 0.1
        omega_max: 0.7
        zeta_min: 0.4
        zeta_max: 1.5
      flap_control:
        flag: False
        omega_min: 2.7
        omega_max: 3.5
        zeta_min: 0.7
        zeta_max: 1.3
      ipc_control:
        flag: False
        Ki_min: 0.0
        Ki_max: 1e-8
  tower:
    outer_diameter:
      flag: False
      lower_bound: 3.87
      upper_bound: 10.0
    layer_thickness:
      flag: False
      lower_bound: 4.e-3
      upper_bound: 2.e-1

merit_figure: 'blade_tip_deflection'

driver:
  optimization:
    flag: False           # Flag to enable optimization
  design_of_experiments:
    flag: True            # Flag to enable design of experiments
    run_parallel: False   # Flag to run using parallel processing
    generator: Uniform    # Type of input generator: [Uniform, FullFact, PlackettBurman, BoxBehnken, LatinHypercube]
    num_samples: 5        # number of samples (Uniform and LatinHypercube only)
    seed: 12345           # random number generator seed (Uniform and LatinHypercube only)

recorder:
    flag: True              # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
