general:
    folder_output: outputs
    fname_output: doe_output
design_variables:
  blade:
    aero_shape:
      twist:
        flag: False  # Flag to optimize the twist
        inverse: False # Flag to determine twist from the user-defined desired margin to stall (defined in constraints)
        n_opt: 8     # Number of control points along blade span
        max_decrease: 0.08722222222222221 # Maximum decrease for the twist in [rad] at the n_opt locations
        max_increase: 0.08722222222222221 # Maximum increase for the twist in [rad] at the n_opt locations
      chord:
        flag: True     # Flag to optimize the chord
        n_opt: 8        # Number of control points along blade span
        max_decrease: 0.2   # Nondimensional lower bound at the n_opt locations
        max_increase: 2.0   # Nondimensional upper bound at the n_opt locations
      af_positions:
        flag: False     # Flag to optimize the airfoil positions
        af_start: 4     # Index of the first airfoil from blade root that can have the location optimized. First airfoil is number 0. Last airfoil is always locked at blade tip.
  control:
    tsr:
      flag: False     # Flag to optimize the rotor tip speed ratio
      minimum: 6
      maximum: 10
  tower:
    outer_diameter:
      flag: False
      lower_bound: 3.87
      upper_bound: 10.0
    layer_thickness:
      flag: False
      lower_bound: 4.e-3
      upper_bound: 2.e-1

merit_figure: 'blade_tip_deflection'

driver:
  optimization:
    flag: False           # Flag to enable optimization
  design_of_experiments:
    flag: True            # Flag to enable design of experiments
    run_parallel: False   # Flag to run using parallel processing
    generator: Uniform    # Type of input generator: [Uniform, FullFact, PlackettBurman, BoxBehnken, LatinHypercube]
    num_samples: 5        # number of samples (Uniform and LatinHypercube only)
    seed: 12345           # random number generator seed (Uniform and LatinHypercube only)

recorder:
    flag: True              # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
