general:
    verbosity: False  # When set to True, the code prints to screen many infos

Analysis_Flags:
    # Control which WISDEM modules are executed.
    # (GOAL) If inputs are missing for a module, a warning will be written to the screen and the module disabled.
    TowerSE: True

yaml:
    validate: False    # When set to True, the code runs a yam validation package. This checks whether the yams has the right formatting.
    path2schema: windIO/windIO/turbine/IEAontology_schema.yaml   # Path to the yams schema to run the validation

xfoil:
    path       : Xfoil/bin/xfoil # Path to xfoil executable. Only used for blades with distributed aerodynamic control devices 

rotorse:
    n_aoa: 200        # Number of angles of attack used to define polars
    n_xy: 200         # Number of angles of coordinate points used to discretize each airfoil
    n_span: 30        # Number of spanwise stations used to define the blade properties

openfast:
    run_openfast: False         # Flag to run aeroelasticse, the wrapper of OpenFAST
    Analysis_Level: 0           # Flag to set the call to OpenFAST. 0 - no call, 1 - generate OpenFAST model, 2 - generate and run OpenFAST model
    FAST_ver: OpenFAST          # Version of OpenFAST, do not change
    dev_branch: True            # Git branch of OpenFAST, do not change
    FAST_exe: openfast/build/glue-codes/openfast/openfast    # Path to OpenFAST executable
    FAST_directory: "/Model_xyz/"  # Path to folder with the OpenFAST input files
    FAST_InputFile: model.fst             # Name of the main OpenFAST input file (.fst)
    path2dll: Controller/libdiscon.so     # Path to the the compiled ROSCO controller
    Turbsim_exe: /install/bin/turbsim_dev   # Path to TurbSim executable
    FAST_namingOut: WISDEM_BAR2011n         # Name of the OpenFAST output files
    FAST_runDirectory: temp_bar             # Path to folder with the OpenFAST output files
    n_simulations: 4  # Number of OpenFAST simulations to run per evaluation of the objective function
    debug_level: 2    # Flag to set the debug level, do not change
    update_hub_nacelle: True
    generate_af_coords: False

tower:             # Options of TowerSE module
  nLC: 1           # Number of design load cases in TowerSE
  wind: PowerWind  # Wind used in TowerSE
  gamma_f: 1.35    # Safety factor for fatigue loads in TowerSE
  gamma_m: 1.3     # Safety factor for material properties in TowerSE
  gamma_n: 1.0     # Safety factor for ...
  gamma_b: 1.1     # Safety factor for ...
  gamma_fatigue: 1.9305  # Safety factor for fatigue loads in TowerSE
  buckling_length: 30    # Buckling parameter in TowerSE
  frame3dd:
    DC: 80.0             # Options of beam solver frame3dd
    shear: True
    geom: True
    dx: 5.0
    nM: 2
    Mmethod: 1
    lump: 0
    tol: 1e-9
    shift: 0.0
    add_gravity: True

servose:
    n_pc: 20                        # Number of wind speeds to compute the power curve
    n_pc_spline: 200                # Number of wind speeds to spline the power curve 
    n_pitch_perf_surfaces: 20       # Number of pitch angles to determine the Cp-Ct-Cq-surfaces
    min_pitch_perf_surfaces: -5.    # Min pitch angle of the Cp-Ct-Cq-surfaces
    max_pitch_perf_surfaces: 30.    # Max pitch angle of the Cp-Ct-Cq-surfaces
    n_tsr_perf_surfaces: 20         # Number of tsr values to determine the Cp-Ct-Cq-surfaces
    min_tsr_perf_surfaces: 2.       # Min TSR of the Cp-Ct-Cq-surfaces
    max_tsr_perf_surfaces: 12.      # Max TSR of the Cp-Ct-Cq-surfaces
    n_U_perf_surfaces: 1            # Number of wind speeds to determine the Cp-Ct-Cq-surfaces
    regulation_reg_III: False       # Flag to derive the regulation trajectory in region III in terms of pitch and TSR
    LoggingLevel: 1                 # {0: write no debug files, 1: write standard output .dbg-file, 2: write standard output .dbg-file and complete avrSWAP-array .dbg2-file
    F_LPFType: 2                    # {1: first-order low-pass filter, 2: second-order low-pass filter}, [rad/s] (currently filters generator speed and pitch control signals)
    F_NotchType: 0                  # Notch filter on generator speed and/or tower fore-aft motion (for floating) {0: disable, 1: generator speed, 2: tower-top fore-aft motion, 3: generator speed and tower-top fore-aft motion}
    IPC_ControlMode: 0              # Turn Individual Pitch Control (IPC) for fatigue load reductions (pitch contribution) {0: off, 1: 1P reductions, 2: 1P+2P reductions}
    VS_ControlMode: 2               # Generator torque control mode in above rated conditions {0: constant torque, 1: constant power, 2: TSR tracking PI control}
    PC_ControlMode: 1               # Blade pitch control mode {0: No pitch, fix to fine pitch, 1: active PI blade pitch control}
    Y_ControlMode: 0                # Yaw control mode {0: no yaw control, 1: yaw rate control, 2: yaw-by-IPC}
    SS_Mode: 1                      # Setpoint Smoother mode {0: no setpoint smoothing, 1: introduce setpoint smoothing}
    WE_Mode: 2                      # Wind speed estimator mode {0: One-second low pass filtered hub height wind speed, 1: Immersion and Invariance Estimator (Ortega et al.)}
    PS_Mode: 0                      # Pitch saturation mode {0: no pitch saturation, 1: peak shaving, 2: Cp-maximizing pitch saturation, 3: peak shaving and Cp-maximizing pitch saturation}
    SD_Mode: 0                      # Shutdown mode {0: no shutdown procedure, 1: pitch to max pitch at shutdown}
    Fl_Mode: 0                      # Floating specific feedback mode {0: no nacelle velocity feedback, 1: nacelle velocity feedback}
    Flp_Mode: 0                     # Flap control mode {0: no flap control, 1: steady state flap angle, 2: Proportional flap control}
